### ISSUE TITLE
bad import $PATH in installation instructions

### ISSUE THREAD

**Issue by alejandrox1** [SD2E/api-user-guide#28]
Installation instructions in [docs/01.install_cli.md](https://github.com/SD2E/api-user-guide/blob/master/docs/01.install_cli.md) have the following:
```
% echo "PATH=\$PATH:$PWD/sd2e-cloud-cli/bin" >> ~/.bashrc
% source ~/.bashrc
```

When `$PATH` is being redefined, the `$` character is being escaped. 
Also, the bin dir of sd2e-cloud-cli should go before `$PATH` in order to avoid sd2e-cloud-cli from replacing any executables that are already in the `$PATH`.

proposed change:
```
$ export PATH=$PWD/sd2e-cloud-cli/bin:$PATH >> ~/.bashrc
$ source ~/.bashrc
```

**Comment by wjallen** [comment]
The PATH import instructions are not bad, they work as intended. 

It is fine to put the CLI bin dir at the front of the PATH, although the reasoning you cite is backwards. Putting the sd2e-cloud-cli before PATH WILL replace any executables (of the same name) that are already in the PATH.

There is a typo in your proposed change - you used 'export' instead of 'echo' and dropped the quotes.

See further comments on pull request #29 

Please let me know if I am misunderstanding your intent somewhere, and I apologize in advance if I am.

**Comment by alejandrox1** [comment]
Proposed change was supposed to be
```
echo 'PATH=$PWD/sd2e-cloud-cli/bin:$PATH' >> ~/.bashrc
```
problem arose on my end from mixing single and double quotes.

Thank you @wjallen for your comment on the order of searching.
